### ISSUE TITLE
No index.php in /public/ - installation fails

### ISSUE THREAD

**Issue by tariquesani** [Erdiko/erdiko#41]
There is no index.php in /public So instructions on http://erdiko.org/getStarted.html fail to get a HelloWorld page. Here are the error log entries.

```
[Fri Apr 21 10:23:01.376936 2017] [autoindex:error] [pid 9745] [client 127.0.0.1:53548] AH01276: Cannot serve directory /home/tariquesani/www/erdiko/public/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Fri Apr 21 10:23:01.915080 2017] [:error] [pid 9745] [client 127.0.0.1:53548] script '/home/tariquesani/www/erdiko/public/index.php' not found or unable to stat, referer: http://erdiko.dev/

```

**Comment by arroyo** [comment]
the web root is /public/default now.  You will will see an index.php file in there, https://github.com/Erdiko/erdiko/blob/master/public/default/index.php

Erdiko now supports context switching.  The initial context is default.  This allows for muti-site and other use cases for context switching.

Thanks for pointing this out.  I created a follow issue to update the erdiko.org installation instructions #42
